# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


TEMPLATE = subdirs
SUBDIRS += HelloWorld/HelloWorld.pro \
    HelloWorldDialog/HelloWorldDialog.pro \
    ManualUIDialog/ManualUIDialog.pro \
    ComplexUIWind/ComplexUIWind.pro \
    CustomObject/CustomObject.pro \
    QGlobalDemo/QGlobalDemo.pro \
    QContainerDemo/QContainerDemo.pro \
    QStringDemo/QStringDemo.pro \
    QSpinBoxDemo/QSpinBoxDemo.pro \
    QSliderDemo/QSliderDemo.pro \
    QDateTimeDemo/QDateTimeDemo.pro \
    QTimeDemo/QTimeDemo.pro \
    QComboBoxDemo/QComboBoxDemo.pro \
    QPlainTextEditDemo/QPlainTextEditDemo.pro \
    QListWidgetDemo/QListWidgetDemo.pro \
    QTreeWidgetDemo/QTreeWidgetDemo.pro \
    QTableWidgetDemo/QTableWidgetDemo.pro \
    QFileSystemModelDemo/QFileSystemModelDemo.pro \
    QStringListModelDemo/QStringListModelDemo.pro \
    QStandardItemModelDemo/QStandardItemModelDemo.pro \
    StandardDialogDemo/StandardDialogDemo.pro \
    CustomDialogDemo/CustomDialogDemo.pro \
    MuliWindowDemo/MuliWindowDemo.pro \
    MDIWindowDemo/MDIWindowDemo.pro \
    TextFileDemo/TextFileDemo.pro \
    BinaryFileDemo/BinaryFileDemo.pro \
    FileDirAccessDemo/FileDirAccessDemo.pro \
    PainterDemo/PainterDemo.pro \
    GraphicsViewDemo/GraphicsViewDemo.pro \
    ChartViewDemo/ChartViewDemo.pro \
    MoreChartViewDemo/MoreChartViewDemo.pro \
    StrengChartViewDemo/StrengChartViewDemo.pro \
    Q3DBarsDemo/Q3DBarsDemo.pro \
    Q3DScatterDemo/Q3DScatterDemo.pro \
    Q3DSurfaceDemo/Q3DSurfaceDemo.pro \
    QSqlTableModelDemo/QSqlTableModelDemo.pro \
    QSqlRelationalTableDemo/QSqlRelationalTableDemo.pro \
    QBatteryBox/QBatteryBox.pro \
    QBatteryBoxDemo/QBatteryBoxDemo.pro
